# Site settings
title: Skogsfors
email: jonatan@skogsfors.net
description: > # this means to ignore newlines until "baseurl:"
  Jenni Skogsfors och Jonatan Skogsfors, frilansande musiker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owners: 
  - name: Jenni Skogsfors
    address:
    - line: Linköping # Feel free to add more lines here 
    email: jenni@skogsfors.net
    telephone: 073-975 98 87
    facebook_username:
    twitter_username:
    github_username:
  - name: Jonatan Skogsfors
    address:
    - line: Linköping # Feel free to add more lines here 
    email: jonatan@skogsfors.net
    telephone: 073-975 98 87
    facebook_username:
    twitter_username:
    github_username:
copyright: Skogsfors

# API settings
google_api_key:

# Build settings
markdown: kramdown
