# Site settings
title: Skogsfors
email: jonatan@skogsfors.net
description: > # this means to ignore newlines until "baseurl:"
  Jenni Skogsfors och Jonatan Skogsfors, frilansande musiker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Jenni & Jonatan Skogsfors
email:
  - jenni@skogsfors.net
  - jonatan@skogsfors.net
facebook_username:
twitter_username:
github_username:
address:
  - line: Linköping
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
