# Site settings
title: Skogsfors
email: jonatan@skogsfors.net
description: > # this means to ignore newlines until "baseurl:"
  Jenni Skogsfors och Jonatan Skogsfors, frilansande musiker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

services:
  - title: Dop
    icon: child
    text: >
      På dop och namngivningar välkomnar vi den lille.
  - title: Vigsel
    icon: heart
    text: >
      Vissa känslor uttrycks bäst i toner. Vi sjunger sångerna
      som är speciella för just er.
  - title: Begravning
    icon: plus
    text: >
      Ett värdigt avsked. Vi sjunger om tacksamhet, saknad
      och hopp.
  - title: Kalas
    icon: birthday-cake
    text: >
      Födelsedag, promovering, jubileum. Du firar, vi sjunger.
      Vi kan även skriva nya hyllningstexter till kända melodier.

# User setting
owners: 
  - name: Jenni Skogsfors
    address:
    - line: Linköping # Feel free to add more lines here 
    email: jenni@skogsfors.net
    telephone: 070-603 34 24
    facebook_username: jenniskogsforsofficial
    twitter_username:
    github_username:
  - name: Jonatan Skogsfors
    address:
    - line: Linköping # Feel free to add more lines here 
    email: jonatan@skogsfors.net
    telephone: 073-975 98 87
    facebook_username:
    twitter_username:
    github_username: jonatanskogsfors
copyright: Skogsfors

# API settings
google_api_key:

# Build settings
markdown: kramdown
